default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: password
  host: db
  port: 5432

development:
  <<: *default
  database: refei_tech_Teste

test:
  adapter: postgresql
  encoding: unicode
  database: test
  pool: 5
  username: test
  password: 123456
  host: db
  port: 5432
